all:
  children:
    cluster:
      master:
        hosts:
          master-1:
            ansible_connection: local
      nodes:
        hosts:
          node1:
            ansible_connection: ssh
            ansible_ssh_private_key_file: "/vagrant/.vagrant/machines/node-1/virtualbox/private_key "
            ansible_host: 192.168.56.101
          node2:
            ansible_connection: ssh
            ansible_ssh_private_key_file: "/vagrant/.vagrant/machines/node-2/virtualbox/private_key "
            ansible_host: 192.168.56.102