name: docker-action
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    
    - name: install npm
      run: apt-get update && apt-get install npm -y

    - name: download dockerlinter
      run: npm install -g dockerlinter

    - name: run diockerlinter
      run: dockerlinter -f dockerfiles/*

      