name: docker-action
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@master
    
    - name: install npm
      run: sudo apt-get update && sudo apt-get install npm -y

    - name: download dockerlinter
      run: sudo npm install -g dockerfilelint # npm install -g dockerlinter

    - name: run diockerlinter
      run: ./bin/dockerfilelint dockerfiles/* # dockerlinter -f dockerfiles/*

      